[project]
name = "predict"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/hadassah/High-level/predict/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.prediction]
path = "contracts/prediction.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
